export const SET_PICKED_DATE = 'SET_PICKED_DATE'
export const ADD_SETTING_DATA = 'ADD_SETTING_DATA'
export const EDIT_SETTING_DATA = 'EDIT_SETTING_DATA'
export const DELETE_SETTING_DATA = 'DELETE_SETTING_DATA'
export const SET_HABIT_DATA = 'SET_HABIT_DATA'
export const SET_USER = 'SET_USER'
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED'
export const RESET_STORE = 'RESET_STORE'
export const
  SET_UNSUB_HABITSETTING = 'SET_UNSUB_HABITSETTING'
export const
  SET_UNSUB_DAYDATA = 'SET_UNSUB_DAYDATA'
